apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busapp-vol-pvc
  namespace: develop
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: example-sc
