apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  labels:
    app: example-app
spec:
  containers:
    - name: example-container
      image: node
      ports:
        - name: port1
          containerPort: 3000
          protocol: TCP
