apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-micro
  name: auth-micro-svc
spec:
  ports:
    - port: 6002
      protocol: TCP
      targetPort: 6002
      nodePort: 32005
  selector:
    app: auth-micro
  type: NodePort
